### ISSUE TITLE
File file-xxx is not ready

### ISSUE THREAD

**Issue by todochenxi** [LearnPrompt/LLMs-cookbook#1]
![图片](https://github.com/LearnPrompt/LLMs-cookbook/assets/108149467/6d560116-7817-4590-a2e9-4df28d7116f4)

开发者你好，问一下，这种情况是正常的嘛

**Comment by todochenxi** [comment]
在创建模型的时候

**Comment by todochenxi** [comment]
哦，文件类型有误，可以用openai.File.list() 查看

**Comment by LearnPrompt** [comment]
谢谢提醒
